### ISSUE TITLE
DGIndexNV: list of files throws error

### ISSUE THREAD

**Issue by LightArrowsEXE** [Jaded-Encoding-Thaumaturgy/vs-source#27]
This error seems to happen if there are any spaces in the path. 
`stdout` doesn't return any useful errors.

Even changing this in `/indexers/DGIndexNV.py:L27` doesn't work:

```diff
-','.join(str(path) for path in files),
+','.join('\"{path}\"' for path in files),
```

I suspect this same error will also happen with the `-o` file.
Since the above code doesn't work for me, I'm not sure what else would.

**Comment by LightArrowsEXE** [comment]
Doing this fixed it, but you can probably handle out a better way to write this:

`/indexers/DGIndexNV.py:L23`
```py
    def get_cmd(self, files: list[SPath], output: SPath) -> list[str]:
        return list(
            map(str, [
                self._get_bin_path(), '-i',
                ','.join(path.name for path in files),
                '-h', '-o', f"{output.parent.name}\\{output.name}",
                '-e'
            ])
        )
```

`/indexers/base.py:157`
```py
        proc = subprocess.Popen(
            list(map(str, self.get_cmd(files, output) + list(cmd_args) + list(self._default_args))),
            text=True, encoding='utf-8', shell=True, cwd=output.get_folder().parent.to_str()
        )
```

The idea is simple: Rather than deal with the path with spaces, we simply cd into the directory containing all the VOBs. There is one major downside to this, though: it breaks if you have source files in multiple directories. So this doesn't necessarily fix the issue itself, it just sidesteps it in the most common use-case where you'd pass multiple files. Because this is the most common use-case, I still it's worth adding some kind of check to see whether all the files are in the same directory or not, but again, this doesn't fix the root issue.

**Comment by Setsugennoao** [comment]
Shouldn't be an issue with the changes made by @jsaowji
